### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [CodeFlowed/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by CodeFlowed** [comment]
Got it. After a quick Google search, I've added `<meta name="viewport" content="width=device-width, initial-scale=1">` to the the head tag of my application.html.erb file. And things look better on mobile. Thanks!

**Comment by MarcoMorawec** [comment]
@CodeFlowed :+1: 

Make sure you close the issue, not that you solved it :)
